from __future__ import annotations

from pathlib import Path
from typing import Optional

import numpy as np
import redis


class RedisItemVectorStore:
    """
    Redis-backed feature store for pre-computed item embeddings.

    Stores vectors using:

        item_vector:<item_id>
            vector -> float32 bytes

    The source embeddings are the production artifacts generated by
    the recommendation model.
    """

    def __init__(
        self,
        redis_url: str = "redis://localhost:6379/0",
        key_prefix: str = "item_vector:",
    ):
        self.redis_url = redis_url
        self.key_prefix = key_prefix

        self.client = redis.Redis.from_url(
            self.redis_url,
            decode_responses=False,
        )

    def ping(self) -> bool:
        """Check whether Redis is reachable."""
        return bool(self.client.ping())

    def _key(self, item_id: str) -> str:
        """Create the Redis key for an item."""
        return f"{self.key_prefix}{item_id}"

    @staticmethod
    def serialize_vector(vector: np.ndarray) -> bytes:
        """Convert a vector to float32 bytes."""
        return np.asarray(vector, dtype=np.float32).tobytes()

    @staticmethod
    def deserialize_vector(raw_bytes: bytes) -> np.ndarray:
        """Convert stored bytes back into a float32 vector."""
        return np.frombuffer(raw_bytes, dtype=np.float32)

    def store_item_vector(
        self,
        item_id: str,
        vector: np.ndarray,
    ) -> None:
        """Store one item vector in Redis."""
        vector = np.asarray(vector, dtype=np.float32)

        self.client.hset(
            self._key(str(item_id)),
            mapping={
                "vector": self.serialize_vector(vector),
            },
        )

    def store_embeddings(
        self,
        item_ids: np.ndarray,
        embeddings: np.ndarray,
        batch_size: int = 500,
    ) -> int:
        """
        Store all item embeddings in Redis.

        Returns the number of stored item vectors.
        """
        item_ids = np.asarray(item_ids)
        embeddings = np.asarray(embeddings, dtype=np.float32)

        if len(item_ids) != len(embeddings):
            raise ValueError(
                f"Item ID count ({len(item_ids)}) does not match "
                f"embedding count ({len(embeddings)})."
            )

        if embeddings.ndim != 2:
            raise ValueError(
                f"Embeddings must be 2-D, got shape {embeddings.shape}."
            )

        total = len(item_ids)

        for start in range(0, total, batch_size):
            end = min(start + batch_size, total)

            pipe = self.client.pipeline(transaction=False)

            for item_id, vector in zip(
                item_ids[start:end],
                embeddings[start:end],
            ):
                pipe.hset(
                    self._key(str(item_id)),
                    mapping={
                        "vector": self.serialize_vector(vector),
                    },
                )

            pipe.execute()

            print(
                f"Stored {end}/{total} item vectors..."
            )

        return total

    def get_item_vector(
        self,
        item_id: str,
    ) -> Optional[np.ndarray]:
        """Retrieve one item vector from Redis."""
        raw = self.client.hget(
            self._key(str(item_id)),
            "vector",
        )

        if raw is None:
            return None

        return self.deserialize_vector(raw)

    def item_exists(self, item_id: str) -> bool:
        """Check whether an item vector exists."""
        return bool(
            self.client.exists(
                self._key(str(item_id))
            )
        )

    def delete_item_vector(self, item_id: str) -> bool:
        """Delete one item vector."""
        return bool(
            self.client.delete(
                self._key(str(item_id))
            )
        )

    def count_item_vectors(self) -> int:
        """Count stored item-vector keys."""
        count = 0

        for _ in self.client.scan_iter(
            match=f"{self.key_prefix}*"
        ):
            count += 1

        return count

    def clear_all_item_vectors(self) -> int:
        """Delete all item-vector keys created by this store."""
        keys = list(
            self.client.scan_iter(
                match=f"{self.key_prefix}*"
            )
        )

        if keys:
            self.client.delete(*keys)

        return len(keys)

    def close(self) -> None:
        """Close the Redis connection."""
        self.client.close()


def load_production_embeddings(
    model_dir: str = "data/processed/model",
):
    """
    Load the actual production item IDs and embeddings.
    """
    model_path = Path(model_dir)

    item_ids_path = model_path / "item_ids.npy"
    embeddings_path = model_path / "item_embeddings.npy"

    if not item_ids_path.exists():
        raise FileNotFoundError(
            f"Item IDs file not found: {item_ids_path}"
        )

    if not embeddings_path.exists():
        raise FileNotFoundError(
            f"Item embeddings file not found: {embeddings_path}"
        )

    item_ids = np.load(
        item_ids_path,
        allow_pickle=True,
    )

    embeddings = np.load(
        embeddings_path,
    )

    return item_ids, embeddings


if __name__ == "__main__":
    item_ids, embeddings = load_production_embeddings()

    print("Production item embeddings loaded.")
    print(f"Item IDs shape        : {item_ids.shape}")
    print(f"Item embeddings shape : {embeddings.shape}")
    print(f"Embedding dtype       : {embeddings.dtype}")

    store = RedisItemVectorStore()

    if not store.ping():
        raise RuntimeError("Redis is not reachable.")

    print("Redis connection: OK")

    stored = store.store_embeddings(
        item_ids,
        embeddings,
        batch_size=500,
    )

    print(f"\nStored item vectors: {stored}")
    print(
        f"Redis item-vector count: "
        f"{store.count_item_vectors()}"
    )

    sample_id = str(item_ids[0])
    retrieved = store.get_item_vector(sample_id)

    if retrieved is None:
        raise RuntimeError(
            f"Failed to retrieve sample item: {sample_id}"
        )

    print(f"\nVerification item ID : {sample_id}")
    print(f"Retrieved shape      : {retrieved.shape}")
    print(f"Retrieved dtype      : {retrieved.dtype}")
    print(
        "Matches source       :",
        np.allclose(
            retrieved,
            embeddings[0],
            rtol=1e-6,
            atol=1e-6,
        ),
    )

    store.close()